appName: client

iterations: 200

minPause: 100
maxPause: 1000

httpClient:
  timeout: 10s
  connectionTimeout: 10s
  connectionRequestTimeout: 10s
  retries: 10

server:
  applicationConnectors:
    - type: http
      port: 6202
  adminConnectors:
    - type: http
      port: 7202
  requestLog:
    appenders: []

applicationServer:
  host: 10.1.10.51
  port: 8202
  healthCheckPort: 9202

# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: WARN

  loggers:
    com.ltceng.serialization.SerializationClientApplication: INFO

  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stderr
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      
    - type: file
      threshold: ALL
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      currentLogFilename: ./application.log
      archivedLogFilenamePattern: ./application-%d{yyyy-MM-dd}-%i.log.gz
      archivedFileCount: 3
      timeZone: UTC
      maxFileSize: 10MB
