clientName: client

server:
  applicationConnectors:
    - type: http
      port: 9000
  adminConnectors:
    - type: http
      port: 9001

applicationServer:
  host: 10.1.10.51
  port: 8082
  healthCheckPort: 8083

# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: WARN

  loggers:
    com.ltceng.serialization.SerializationClientApplication: INFO

  appenders:
    - type: console
      threshold: INFO
      target: stderr
      
    - type: file
      threshold: INFO
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      currentLogFilename: ./application.log
      archivedLogFilenamePattern: ./application-%d{yyyy-MM-dd}-%i.log.gz
      archivedFileCount: 3
      timeZone: UTC
      maxFileSize: 10MB
