- hosts: all

  vars:
    srcDir: "/home/kvandegrift/Prototypes/Client/"
    targetDir: "/home/kvandegrift/Deployed/Client"
    nodeId: "{{ ansible_eth0.ipv4.address.split('.')[-1] }}"
    appIds: 
      - "{{ nodeId }}1"
      - "{{ nodeId }}2"

  tasks:
    - name: Create deployment folders.
      file: path={{ targetDir }}{{ item }} state=absentls

      file: path={{ targetDir }}{{ item }} state=directory
      with_items:
        - "{{ appIds }}"
    - name: Deploy config files.
      copy:  src={{ item[0] }} dest={{ targetDir }}{{ item[1] }}
      with_nested:
        - "{{ srcDir }}/config.yml"
        - appIds
    - name: Deploy app files.
      copy:  src={{ item[0] }} dest={{ targetDir }}{{ item[1] }}
      with_nested:
        - "{{ srcDir }}/target/SerializationClient-1.0-SNAPSHOT.jar"
        - appIds
    - name: Update node name in config file.
      replace: 'dest={{ targetDir }}{{ item }}/config.yml regexp="^appName: client" replace="appName: Client{{ item }}"'
      with_items:
        - "{{ appIds }}"
    - name: Update app port in config file.
      replace: 'dest={{ targetDir }}{{ item }}/config.yml regexp="^      port: 6000" replace="      port: 6{{ item }}"'
      with_items:
        - "{{ appIds }}"
    - name: Update app admin port in config file.
      replace: 'dest={{ targetDir }}{{ item }}/config.yml regexp="^      port: 7000" replace="      port: 7{{ item }}"'
      with_items:
        - "{{ appIds }}"
    - name: Update app server ip in config file.
      replace: 'dest={{ targetDir }}{{ item }}/config.yml regexp="^  host: 10.1.10.202" replace="  host: {{ inventory_hostname }}"'
      with_items:
        - "{{ appIds }}"
