appName: serialization

#NoSQL database
noSqlStore:
  storeName: serialization
  durability:
    masterSyncPolicy: SYNC
    replicaSyncPolicy: WRITE_NO_SYNC
    replicaAckPolicy: SIMPLE_MAJORITY
  consistency: 
    type: ABSOLUTE
  maxTimeoutWait: 5000
  attemptTimeoutWait: 500
  helperNodes:
    - hostName: node1
      port: 5000
    - hostName: node2
      port: 5000
    - hostName: node3
      port: 5000
    - hostName: node4
      port: 5000
    - hostName: node5
      port: 5000
    - hostName: node6
      port: 5000

server:
  applicationConnectors:
    - type: http
      port: 8000
  adminConnectors:
    - type: http
      port: 9000
  requestLog:
    appenders: []

metrics:
  reporters:
    - type: graphite
      host: 10.1.10.202
      port: 2003
      prefix: serialization

# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: WARN

  loggers:
    com.ltceng.serialization.SerializationApplication: INFO
    com.ltceng.serialization.resources.SequenceResource: DEBUG
    com.ltceng.serialization.db.SequenceDAO: TRACE

  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      
    - type: file
      threshold: ALL
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      currentLogFilename: ./application.log
      archivedLogFilenamePattern: ./application-%d{yyyy-MM-dd}-%i.log.gz
      archivedFileCount: 3
      timeZone: UTC
      maxFileSize: 10MB
