serverName: serialization

#NoSQL database
noSqlStore:
  storeName: serialization
  durability:
    masterSyncPolicy: SYNC
    replicaSyncPolicy: WRITE_NO_SYNC
    replicaAckPolicy: SIMPLE_MAJORITY
  consistency: 
    type: ABSOLUTE
  helperNodes:
    - hostName: suter-lab2
      port: 5000
    - hostName: grm_lb_software_1
      port: 5000
    - hostName: grm_lb_software_2
      port: 5000

server:
  applicationConnectors:
    - type: http
      port: 8082
  adminConnectors:
    - type: http
      port: 8083

metrics:
  reporters:
    - type: graphite
      host: 10.1.10.23
      port: 2003
      prefix: serialization

# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: WARN

  loggers:
    com.ltceng.serialization.SerializationApplication: INFO

  appenders:
    - type: console
      threshold: INFO
      
    - type: file
      threshold: INFO
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      currentLogFilename: ./application.log
      archivedLogFilenamePattern: ./application-%d{yyyy-MM-dd}-%i.log.gz
      archivedFileCount: 3
      timeZone: UTC
      maxFileSize: 10MB